### PR TITLE
adding dedicated ai app templates

### PR DESCRIPTION
**Pull request by dantelmomsft**

### CODE REVIEW

**Review by karianna — COMMENTED** [review]
Is there a way we can dynamically create this list?

**Comment by dantelmomsft** [comment]
> Is there a way we can dynamically create this list?

@karianna The huge part is reviewing them, trying to run and evaluate overall code/documentation quality. Maybe some checks could be automated. 
However, in this list we are tracking apps which aren't (yet) included in other catalogue like [AI Apps Gallery](http://aka.ms/aiapps) (which has  automatic validation pipeline in place) but can still be reusable IP.

**Review by aarthiem — APPROVED** [review]
Looks good, thanks Davide!

**Review by azooinmyluggage — COMMENTED** [review]
LGTM

**Pull request merged**
